services:
  testdb:
    image: docker.io/postgres:14.8-alpine3.18
    restart: always
    container_name: test_db_container
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d test_db -U test_user"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "test_user"
      POSTGRES_PASSWORD: "password"
    ports:
      - "5432:5432"
    volumes:
      - ./db_dump:/docker-entrypoint-initdb.d

  testapppytest:
    build:
      context: .
      dockerfile: ./Dockerfile.pytest
    container_name: test_app_pytest
    network_mode: "host"
    depends_on:
      testdb:
        condition: service_healthy
    volumes:
      - shared-volume:/app/templates/
    command: ["pytest", "/app/test_db_operations.py", "-s", "-v", "--html=/app/templates/report.html", "--self-contained-html"]
    
  flasktestresults:
    build:
      context: .
      dockerfile: ./Dockerfile.flask
    restart: always
    container_name: flask_test_results
    depends_on:
      testdb:
        condition: service_healthy
    volumes:
      - shared-volume:/app/templates/
    ports:
      - "5000:5000"
    command: ["python3", "/app/flask_test_results.py"]


volumes:
  shared-volume:
